server:
  port: 31000
spring:
  application:
    name: nm-service-manage-cms-client
  data:
    mongodb:
      uri: mongodb://localhost:27017/nm_cms
      database: nm_cms
    rabbitmq:
      host: 127.0.0.1
      port: 5672
      username: guest
      password: guest
      virtualHost: /
ningmeng:
  mq:
    queue: queue_cms_postpage_01
    routingKey: 5a751fab6abb5044e0d19ea1